### ISSUE TITLE
[4.0.6] Validate-Method throws System.TypeInitializationException : The type initializer for 'DryIoc.OpenGenericTypeKey' threw an exception.

### ISSUE THREAD

**Issue by Fruchuxs** [dadhi/DryIoc#173]
Hello again,

DryIoc 4.0.6 works fine, but our Registration Test who calls Validate() on the configured Container throws an exception:

```
Result StackTrace:	
at DryIoc.OpenGenericTypeKey.ToExpression(Func`2 fallbackConverter) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 2277
   at DryIoc.ContainerTools.GetRequestExpression(IContainer container, Request request, RequestFlags requestParentFlags) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 3243
   at DryIoc.ContainerTools.GetRequestExpression(IContainer container, Request request, RequestFlags requestParentFlags) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 3214
   at DryIoc.ContainerTools.GetRequestExpression(IContainer container, Request request, RequestFlags requestParentFlags) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 3214
   at DryIoc.ContainerTools.GetRequestExpression(IContainer container, Request request, RequestFlags requestParentFlags) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 3214
   at DryIoc.ContainerTools.GetRequestExpression(IContainer container, Request request, RequestFlags requestParentFlags) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 3214
   at DryIoc.ContainerTools.GetRequestExpression(IContainer container, Request request, RequestFlags requestParentFlags) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 3214
   at DryIoc.ContainerTools.GetRequestExpression(IContainer container, Request request, RequestFlags requestParentFlags) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 3214
   at DryIoc.ContainerTools.GetRequestExpression(IContainer container, Request request, RequestFlags requestParentFlags) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 3214
   at DryIoc.ContainerTools.GetRequestExpression(IContainer container, Request request, RequestFlags requestParentFlags) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 3214
   at DryIoc.ContainerTools.GetRequestExpression(IContainer container, Request request, RequestFlags requestParentFlags) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 3214
   at DryIoc.ContainerTools.GetRequestExpression(IContainer container, Request request, RequestFlags requestParentFlags) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 3214
   at DryIoc.ContainerTools.GetRequestExpression(IContainer container, Request request, RequestFlags requestParentFlags) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 3214
   at DryIoc.ContainerTools.GetRequestExpression(IContainer container, Request request, RequestFlags requestParentFlags) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 3214
   at DryIoc.Resolver.CreateResolutionExpression(Request request, Boolean opensResolutionScope) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 6037
   at DryIoc.ReflectionFactory.TryResolveParameterExpressions(ParameterInfo[] parameters, Func`2 parameterServiceInfoSelector, Request request, Int32& usedInputArgAndCustomValueCount) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 8451
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 8380
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 7865
   at DryIoc.ReflectionFactory.TryResolveParameterExpressions(ParameterInfo[] parameters, Func`2 parameterServiceInfoSelector, Request request, Int32& usedInputArgAndCustomValueCount) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 8451
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 8380
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 7865
   at DryIoc.ReflectionFactory.TryResolveParameterExpressions(ParameterInfo[] parameters, Func`2 parameterServiceInfoSelector, Request request, Int32& usedInputArgAndCustomValueCount) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 8451
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 8380
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 7865
   at DryIoc.ReflectionFactory.TryResolveParameterExpressions(ParameterInfo[] parameters, Func`2 parameterServiceInfoSelector, Request request, Int32& usedInputArgAndCustomValueCount) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 8451
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 8380
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 7865
   at DryIoc.ReflectionFactory.TryResolveParameterExpressions(ParameterInfo[] parameters, Func`2 parameterServiceInfoSelector, Request request, Int32& usedInputArgAndCustomValueCount) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 8451
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 8380
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 7865
   at DryIoc.ReflectionFactory.TryResolveParameterExpressions(ParameterInfo[] parameters, Func`2 parameterServiceInfoSelector, Request request, Int32& usedInputArgAndCustomValueCount) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 8451
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 8380
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 7865
   at DryIoc.ReflectionFactory.TryResolveParameterExpressions(ParameterInfo[] parameters, Func`2 parameterServiceInfoSelector, Request request, Int32& usedInputArgAndCustomValueCount) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 8451
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 8380
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 7865
   at DryIoc.ReflectionFactory.TryResolveParameterExpressions(ParameterInfo[] parameters, Func`2 parameterServiceInfoSelector, Request request, Int32& usedInputArgAndCustomValueCount) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 8451
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 8380
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 7865
   at DryIoc.ReflectionFactory.TryResolveParameterExpressions(ParameterInfo[] parameters, Func`2 parameterServiceInfoSelector, Request request, Int32& usedInputArgAndCustomValueCount) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 8451
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 8380
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 7865
   at DryIoc.WrappersSupport.GetKeyValuePairExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 3852
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 7865
   at DryIoc.WrappersSupport.GetArrayExpression(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 3712
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 7865
   at DryIoc.ReflectionFactory.TryResolveParameterExpressions(ParameterInfo[] parameters, Func`2 parameterServiceInfoSelector, Request request, Int32& usedInputArgAndCustomValueCount) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 8451
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 8380
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 7865
   at DryIoc.ReflectionFactory.TryResolveParameterExpressions(ParameterInfo[] parameters, Func`2 parameterServiceInfoSelector, Request request, Int32& usedInputArgAndCustomValueCount) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 8451
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 8380
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 7865
   at DryIoc.WrappersSupport.GetArrayExpression(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 3712
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 7865
   at DryIoc.ReflectionFactory.TryResolveParameterExpressions(ParameterInfo[] parameters, Func`2 parameterServiceInfoSelector, Request request, Int32& usedInputArgAndCustomValueCount) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 8451
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 8380
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 7865
   at DryIoc.Container.DryIoc.IContainer.GetDecoratorExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 1341
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 7842
   at DryIoc.ContainerTools.Validate(IContainer container, ServiceInfo[] roots) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 3182
   at tests.ServiceRegistration.ServiceRegistrationTests.ServiceRegistrationTests() in D:\dev\projects\tests\ServiceRegistration\ServiceRegistrationTests.cs:line 52
--ContainerException
   at DryIoc.Throw.ThrowIfNull[T](T arg, Int32 error, Object arg0, Object arg1, Object arg2, Object arg3) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 10643
   at DryIoc.ReflectionTools.SingleConstructor(Type type, Boolean includeNonPublic) in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 11075
   at DryIoc.OpenGenericTypeKey..cctor() in D:\Dev\DryIoc\src\DryIoc\Container.cs:line 2279
Result Message:	
System.TypeInitializationException : The type initializer for 'DryIoc.OpenGenericTypeKey' threw an exception.
  ----> DryIoc.ContainerException : Unable to find a single constructor in Type DryIoc.OpenGenericTypeKey (including non-public=False)
```

**Comment by dadhi** [comment]
Are you using DryIoc or DryIoc.dll package?

**Comment by Fruchuxs** [comment]
We use the DLL package.

**Comment by dadhi** [comment]
Hmm, ok, will check.

**Comment by dadhi** [comment]
@Fruchuxs v4.0.7 with the fix is out to NuGet

**Comment by Fruchuxs** [comment]
Works fine, thank u again!
