### ISSUE TITLE
Azure Function DI issue - Anonymously Hosted DynamicMethods Assembly. Object reference not set.

### ISSUE THREAD

**Issue by AbhishekTripathi** [dadhi/DryIoc#180]
I am using 
Azure Functions Core Tools (2.7.1595 Commit hash: dbf9a30b5775570ceac0baf6338ef4e88746f3c4)
Function Runtime Version: 2.0.12653.0

While working on a Azure ƒn project with the new DI approach, I hit following error. I am yet to find the root cause but it is a runtime issue and doesn't seem to be coming out of my code or DI registration.

The error on Function Console is:
` Anonymously Hosted DynamicMethods Assembly: Object reference not set to an instance of an object.`

## Screenshot:
![image](https://user-images.githubusercontent.com/1847545/65278981-82718600-db2d-11e9-9274-d1f6c601c9c5.png)

## StackTrace
```
   at DryIoc.Factory.<>c__DisplayClass26_1.<ApplyReuse>b__2() in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6596
   at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7840
   at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7825
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6595
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6555
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7074
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6545
   at DryIoc.Factory.GetDelegateOrDefault(Request request) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6625
   at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 210
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 195
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.ScopedServiceProvider.GetService(Type serviceType) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\DependencyInjection\ScopedServiceProvider.cs:line 25
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultJobActivator.CreateInstance[T](IServiceProvider serviceProvider) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultJobActivator.cs:line 42
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultJobActivator.CreateInstance[T](IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultJobActivator.cs:line 32
   at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory`1.<>c__DisplayClass1_1.<.ctor>b__0(IFunctionInstanceEx i) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.cs:line 20
   at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory`1.Create(IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.cs:line 26
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.CreateInstance(IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 44
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ParameterHelper.Initialize() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 847
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<TryExecuteAsyncCore>d__16.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 116
```

**Comment by AbhishekTripathi** [comment]
I found that one of my Injection doesn't contain appropriate parameter for initializing the singleton instance. Fixing that resolves this issue. However, the error message is very misleading.

**Comment by dadhi** [comment]
Thanks for posting the details. Will look anyway.

**Comment by dadhi** [comment]
What DryIoc version did you use?

**Comment by AbhishekTripathi** [comment]
Since I haven't explicitly referenced this package, I am unaware. I am not able to find it in the dependencies either. To reproduce, register a dependency which has a single public constructor and it takes an argument. Do not provide the argument while registering the dependency. Just to state again, this is an Azure Function application with the new DI approach.

If it helps, I am providing below some relevant dependencies which may give you some clue -

![image](https://user-images.githubusercontent.com/1847545/65317096-6dcbd700-db9b-11e9-99aa-d3d6f15b9b73.png)

![image](https://user-images.githubusercontent.com/1847545/65317158-90f68680-db9b-11e9-92ad-91ece61afeea.png)

**Comment by dadhi** [comment]
The same problem as it was for DryIoc.WepApi and DryIoc.Mvc - the default ASP .NET convention `IServiceProvider.GetService(Type t)` is to return `null` if service is not resolved to enable the fallback to default framework resolution mechanism.

**Comment by dadhi** [comment]
@AbhishekTripathi 
#330 is postponed but you may enable #331 for the diagnostics purposes

**Comment by GregoryLeeWhite** [comment]
I ran into this issue when trying to register a service with durable functions.
The root cause ended up being an optional constructor argument.

`public MyService(IOtherDependency otherDependency, int optionalArgument = 15)`
👆 caused the error.

```csharp
public MyService(IOtherDependency otherDependency, int? optionalArgument = null)
{
    _otherDependency = otherDependency;
    _optionalArgument = optionalArgument ?? 15;
}
```
👆 resolved my issue.

**Comment by dadhi** [comment]
@GregoryLeeWhite Hi, what version of DryIoc did you use?

**Comment by GregoryLeeWhite** [comment]
@dadhi Having a hard time finding out the exact version because it looks like it came with `WebJobs.Script.WebHost`.  Based on my exception details, the error was occurring in [this class](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs).

**Comment by develorem** [comment]
@GregoryLeeWhite Just FYI, I landed on this Issue and you pointing out that the optional parameter was an issue helped me so much. I'm not even using Dryloc, but was hitting the 'Anonymously Hosted DynamicMethods Assembly' error with just an Azure Function and default IoC, and it turned out that the extra optional parameter was the issue! Thanks so much brother.
