### ISSUE TITLE
public static StringBuilder Print(this StringBuilder s, Type type, Func<Type, string> getTypeName = null) throws exception

### ISSUE THREAD

**Issue by puchs** [dadhi/DryIoc#206]
I am using the nuget package 4.1.0-preview-04. this is the newest I could find.

The issue can be reproduced by looking for a type in the dll of a .net core program, that does not contain any applicable type:

container.RegisterMany(
          new[] { Assembly.LoadFrom("DryIocTest.dll") },
          type => type.IsAssignableTo(typeof(IService)) && type.IsClass && !type.IsAbstract);

This should throw a DryIoc.ContainerException, but it does not, because in the process of creating this exception , the method

public static StringBuilder Print(this StringBuilder s, Type type, Func<Type, string> getTypeName = null)

throws a System.ArgumentOutOfRangeException in line 12864:

s.Append(typeName.Substring(0, typeName.IndexOf('`')).Replace('+', '.')).Append('<');

because the dll contains compiler generated types, whose names do not contain a backtick: '`'.
It does contain - among other types - also types with names like "<>c" or "data".

A possible solution would be to filter compiler generated types with 

if (Attribute.GetCustomAttribute(type, typeof(CompilerGeneratedAttribute)) != null)
   return s;

at the beginning of the method and check for "data" or similar types later in the method. But perhaps you prefer a different solution.

I have read the contributing guidelines and would love to write an actual test for this issue, but since it revolves around reading the dll of a .net core program I am not sure how to do this in a unit-test. This is why I have attached a zip file containing a minimal VS19 solution showcasing the problem.
[DryIocTest.zip](https://github.com/dadhi/DryIoc/files/4039144/DryIocTest.zip)

**Comment by dadhi** [comment]
Thanks for the finding - I will look.
Coold you post the whole stack-trace? 
I am interested in the calling code too because the `Print` is likely to be used for composing the other Exception message.

**Comment by puchs** [comment]
Here you go:

System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at DryIoc.PrintTools.Print(StringBuilder s, Type type, Func`2 getTypeName) in C:\Users\puchs\.nuget\packages\dryioc\4.1.0-preview-04\contentFiles\cs\netstandard2.0\DryIoc\Container.cs:line 12864
   at DryIoc.PrintTools.Print(StringBuilder s, Object x, String quote, String itemSeparator, Func`2 getTypeName) in C:\Users\puchs\.nuget\packages\dryioc\4.1.0-preview-04\contentFiles\cs\netstandard2.0\DryIoc\Container.cs:line 12803
   at DryIoc.PrintTools.<>c__DisplayClass1_0.<Print>b__1(StringBuilder _, Object o) in C:\Users\puchs\.nuget\packages\dryioc\4.1.0-preview-04\contentFiles\cs\netstandard2.0\DryIoc\Container.cs:line 12811
   at DryIoc.PrintTools.Print(StringBuilder s, IEnumerable items, String separator, Action`2 printItem) in C:\Users\puchs\.nuget\packages\dryioc\4.1.0-preview-04\contentFiles\cs\netstandard2.0\DryIoc\Container.cs:line 12835
   at DryIoc.PrintTools.Print(StringBuilder s, Object x, String quote, String itemSeparator, Func`2 getTypeName) in C:\Users\puchs\.nuget\packages\dryioc\4.1.0-preview-04\contentFiles\cs\netstandard2.0\DryIoc\Container.cs:line 12803
   at DryIoc.ContainerException.Print(Object arg) in C:\Users\puchs\.nuget\packages\dryioc\4.1.0-preview-04\contentFiles\cs\netstandard2.0\DryIoc\Container.cs:line 11819
   at DryIoc.ContainerException.Of(ErrorCheck errorCheck, Int32 errorCode, Object arg0, Object arg1, Object arg2, Object arg3, Exception innerException) in C:\Users\puchs\.nuget\packages\dryioc\4.1.0-preview-04\contentFiles\cs\netstandard2.0\DryIoc\Container.cs:line 11809
   at DryIoc.Throw.It(Int32 error, Object arg0, Object arg1, Object arg2, Object arg3) in C:\Users\puchs\.nuget\packages\dryioc\4.1.0-preview-04\contentFiles\cs\netstandard2.0\DryIoc\Container.cs:line 12169
   at DryIoc.Registrator.RegisterMany(IRegistrator registrator, IEnumerable`1 implTypes, Func`2 getServiceTypes, Func`2 getImplFactory, Func`3 getServiceKey, Nullable`1 ifAlreadyRegistered) in C:\Users\puchs\.nuget\packages\dryioc\4.1.0-preview-04\contentFiles\cs\netstandard2.0\DryIoc\Container.cs:line 6530
   at DryIoc.Registrator.RegisterMany(IRegistrator registrator, IEnumerable`1 implTypes, IReuse reuse, Made made, Setup setup, Nullable`1 ifAlreadyRegistered, Func`2 serviceTypeCondition, Boolean nonPublicServiceTypes, Object serviceKey) in C:\Users\puchs\.nuget\packages\dryioc\4.1.0-preview-04\contentFiles\cs\netstandard2.0\DryIoc\Container.cs:line 6563
   at DryIoc.Registrator.RegisterMany(IRegistrator registrator, IEnumerable`1 implTypeAssemblies, Func`2 serviceTypeCondition, IReuse reuse, Made made, Setup setup, Nullable`1 ifAlreadyRegistered, Boolean nonPublicServiceTypes, Object serviceKey) in C:\Users\puchs\.nuget\packages\dryioc\4.1.0-preview-04\contentFiles\cs\netstandard2.0\DryIoc\Container.cs:line 6555
   at DryIocTest.Program.Main() in D:\Users\puchs\uCloud\Programming\DryIocTest\DryIocTest\DryIocTest\Program.cs:line 13
