### ISSUE TITLE
Web Api SignalR. Cannot resolve hub instance on connection timeout.

### ISSUE THREAD

**Issue by YuriySamoylenko** [dadhi/DryIoc#292]
When client is disconnected Signalr tries to instantiate a hub for calling OnDisconnected event handler.
It works when client disconnects intentionally (calling stop connection on client, or closing browser tab).
But if disconnection happens when connection timeout expires exception is thrown. (default timeout is 30 seconds)

`DryIoc.ContainerException: 'code: ScopeIsDisposed; message: Scope "{IsDisposed=true, Name=~WebRequestScopeName}" is disposed and scoped instances are disposed and no longer available.'

   at DryIoc.Interpreter.InterpretGetNameScopedViaFactoryDelegate(IResolverContext r, MethodCallExpression callExpr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec) in /_/src/DryIoc/Container.cs:line 3708
   at DryIoc.Interpreter.TryInterpretMethodCall(IResolverContext r, Expression expr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 3275
   at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 2915
   at DryIoc.Interpreter.TryInterpretAndUnwrapContainerException(IResolverContext r, Expression expr, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 2753
   at DryIoc.Container.ResolveAndCacheKeyed(Int32 serviceTypeHash, Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Object scopeName, Type requiredServiceType, Request preResolveParent, Object[] args) in /_/src/DryIoc/Container.cs:line 518
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Type requiredServiceType, Request preResolveParent, Object[] args) in /_/src/DryIoc/Container.cs:line 427
   at DryIoc.Interpreter.InterpretResolveMethod(IResolverContext resolver, IList`1 callArgs, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 3502
   at DryIoc.Interpreter.TryInterpretMethodCall(IResolverContext r, Expression expr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 3385
   at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 2915
   at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 2897
   at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, Object paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 2897
   at DryIoc.Interpreter.TryInterpretAndUnwrapContainerException(IResolverContext r, Expression expr, Boolean useFec, Object& result) in /_/src/DryIoc/Container.cs:line 2753
   at DryIoc.Container.ResolveAndCacheKeyed(Int32 serviceTypeHash, Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Object scopeName, Type requiredServiceType, Request preResolveParent, Object[] args) in /_/src/DryIoc/Container.cs:line 518
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Type requiredServiceType, Request preResolveParent, Object[] args) in /_/src/DryIoc/Container.cs:line 427
   at DryIoc.Resolver.Resolve[TService](IResolver resolver, Type requiredServiceType, IfUnresolved ifUnresolved, Object[] args, Object serviceKey) in /_/src/DryIoc/Container.cs:line 7613
   at DryIoc.SignalR.DryIocHubActivator.Create(HubDescriptor descriptor) in D:\Dev\DryIoc\src\DryIoc.SignalR\DryIocSignalR.cs:line 170
   at Microsoft.AspNet.SignalR.Hubs.DefaultHubManager.ResolveHub(String hubName) in /_/src/Microsoft.AspNet.SignalR.Core/Hubs/Lookup/DefaultHubManager.cs:line 96
   at Microsoft.AspNet.SignalR.Hubs.HubDispatcher.CreateHub(IRequest request, HubDescriptor descriptor, String connectionId, StateChangeTracker tracker, Boolean throwIfFailedToCreate) in /_/src/Microsoft.AspNet.SignalR.Core/Hubs/HubDispatcher.cs:line 453`

Can be reproduced by turning off internet connection on signalr client machine or waiting at breakpoint in browser devtools for js signalr client.
Exception can be caught only if 'Enable Just My Code' option is not selected in Visual Studio debugger.
In runtime exception is silent. Nothing happens, just OnDisconnected hub method is not called.

**Comment by dadhi** [comment]
@YuriySamoylenko Hi there,

Are you using `DryIoc.SignalR` package?
and what is the version of SignalR?

**Comment by YuriySamoylenko** [comment]
Hi @dadhi ,
yes I am using DryIoc.SignalR v4.0.0
SignalR v2.4.1
DryIoc v4.2.4

**Comment by dadhi** [comment]
@YuriySamoylenko 
I did not touch the SignalR extension for a long time and the SignalR seems like advanced into the AspNetCore and newer versions. So it would be hard for me to understand your problem case (read, it requires significant time). So it would be much faster if you look into it yourself. 

The SignalR extension is a single file https://github.com/dadhi/DryIoc/blob/master/src/DryIoc.SignalR/DryIocSignalR.cs 
with a small amount of code excluding the comments. You can just copy it directly to you project and experiment with the integration. Please keep me posted if you find something interesting.

**Comment by YuriySamoylenko** [comment]
I got it working.
I used method described [here](https://github.com/simpleinjector/SimpleInjector/issues/232) for SimpleInjector.
Additionally to registration in `DryIoc.SignalR.WithSihnalR` I added custom implementation of `HubDispatcher`

```
 public class DryIocHubDispatcher : HubDispatcher
    {
        private readonly IContainer container;

        public DryIocHubDispatcher(IContainer container, HubConfiguration configuration) : base(configuration)
        {
            this.container = container;
        }

        protected override Task OnConnected(IRequest request, string connectionId)
        {
            return this.Invoke(() => base.OnConnected(request, connectionId));
        }

        protected override Task OnReceived(IRequest request, string connectionId, string data)
        {
            return this.Invoke(() => base.OnReceived(request, connectionId, data));
        }

        protected override Task OnDisconnected(IRequest request, string connectionId, bool stopCalled)
        {
            return this.Invoke(() => base.OnDisconnected(request, connectionId, stopCalled));
        }

        protected override Task OnReconnected(IRequest request, string connectionId)
        {
            return this.Invoke(() => base.OnReconnected(request, connectionId));
        }

        private async Task Invoke(Func<Task> method)
        {
            using (this.container.OpenScope())
            {
                await method();
            }
        }
    }
```

Registered it in a container like this:
`container.Register<DryIocHubDispatcher>(made: Made.Of(() => new DryIocHubDispatcher(container, config)));`

And added it to signalr initialization:
`appBuilder.Map("/signalr", app => app.RunSignalR<DryIocHubDispatcher>(config));`

**Comment by dadhi** [comment]
@YuriySamoylenko 

Glad it worked. Thanks for your findings and thanks to SimpmeInjector folks :)

Couple of possible improvements (but need to be checked)...

You don't need the whole `IContainer` to `OpenScope` - `IResolverContext` is enough.
More important, DryIoc is automatically injecting "correct" container instance for its implemented interfaces, so that:

```cs
    public class DryIocHubDispatcher : HubDispatcher
    {
        private readonly IResolverContext resolver;

        public DryIocHubDispatcher(IResolverContext resolver, HubConfiguration configuration) : base(configuration)
        {
            this.resolver = resolver;
        }
//...
```

and registration may look like:

```cs
container.Register<DryIocHubDispatcher>();
container.RegisterInstance(config);
```

Btw, I would like to add your code to the `SignalR` extension if it is fine with you, or you may create a PR. What do you think?

**Comment by dadhi** [comment]
fixed in DryIoc.SignalR v4.1.0 (adding DryIocHubDispatcher)
