### ISSUE TITLE
Resolve with FactoryMethod of instance throws DryIoc.ContainerException

### ISSUE THREAD

**Issue by hygehyge** [dadhi/DryIoc#367]
DryIoc.dll 4.7.2

I have these interface and factory classes.
As you see, one of factory methods is static.
```csharp
public interface IAbstraction<T>
{
    string Description { get; }
}

public class Abstraction<T> : IAbstraction<T>
{
    public string Description { get; } = typeof(T).Name;
}

public class Factory
{
    public IAbstraction<T> Create<T>()
    {
        return new Abstraction<T>();
    }
}

public class StaticFactory
{
    public static IAbstraction<T> Create<T>()
    {
        return new Abstraction<T>();
    }
}
```

When I register interface with static factory method like below, `IAbstraction<string>` is resolved and test is passed.
```csharp
//Pass
[Fact]
public void Test_StaticFactory()
{
    var container = new Container();
    var factoryMethod = FactoryMethod.Of(typeof(StaticFactory).GetMethods().Single(m => m.Name == "Create" && m.IsGenericMethodDefinition));
    container.Register(typeof(IAbstraction<>), made: Made.Of(factoryMethod: factoryMethod));

    IAbstraction<string> abs = null;
    Should.NotThrow(() => abs = container.Resolve<IAbstraction<string>>());
    abs.ShouldNotBeNull();
    abs.Description.ShouldBe("String");
}
```

But when I use instance factory method instead of static one, DryIoc throws Excecption.
```csharp
 //FAIL!!
[Fact]
public void Test_Factory()
{
    var factory = new Factory();
    var container = new Container();
    var factoryMethod = FactoryMethod.Of(typeof(Factory).GetMethods().Single(m => m.Name == "Create" && m.IsGenericMethodDefinition), factoryInstance: factory);
    container.Register(typeof(IAbstraction<>), made: Made.Of(factoryMethod: factoryMethod));

    IAbstraction<string> abs = null;
    Should.NotThrow(() => abs = container.Resolve<IAbstraction<string>>());//<-- this throws
    abs.ShouldNotBeNull();
    abs.Description.ShouldBe("String");
}

/*
DryIoc.ContainerException: code: Error.PassedMemberIsNotStaticButInstanceFactoryIsNull;
message: The member info DryiocTest.IAbstraction`1[System.String] Create[String]() passed to `Made.Of` or `FactoryMethod.Of` is NOT static, but instance factory is not provided or null
   at DryIoc.Throw.It(Int32 error, Object arg0, Object arg1, Object arg2, Object arg3) in /_/src/DryIoc/Container.cs:line 13572
   at DryIoc.FactoryMethod.Of(MemberInfo ctorOrMethodOrMember, ServiceInfo factoryInfo) in /_/src/DryIoc/Container.cs:line 6334
   at DryIoc.ReflectionFactory.GetClosedFactoryMethodOrDefault(FactoryMethod factoryMethod, Type[] serviceTypeArgs, Request request, Boolean ifErrorReturnDefault) in /_/src/DryIoc/Container.cs:line 11528
   at DryIoc.ReflectionFactory.ClosedGenericFactoryGenerator.GetGeneratedFactory(Request request, Boolean ifErrorReturnDefault) in /_/src/DryIoc/Container.cs:line 11191
   at DryIoc.Container.DryIoc.IContainer.ResolveFactory(Request request) in /_/src/DryIoc/Container.cs:line 1065
   at DryIoc.Container.ResolveAndCache(Int32 serviceTypeHash, Type serviceType, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 367
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 356
   at DryIoc.Resolver.Resolve[TService](IResolver resolver, IfUnresolved ifUnresolved) in /_/src/DryIoc/Container.cs:line 8008
   at DryiocTest.UnitTest1.Test_Factory() in D:\VCS\Deletable\DryiocTest\DryiocTest\UnitTest1.cs:line 48
*/
```

I think `FactoryMethod.Of` is provided instance by `factoryInstance: factory`.
Am I missing something?
Thanks.

**Comment by dadhi** [comment]
@hygehyge Hi, thanks for posting and for the tests.
I think the problem is related to the method being open-generic and the exception message is misleading... I need to check it.

**Comment by dadhi** [comment]
@hygehyge This is indeed a bug of using together a generic method and the `factoryInstance`.
Until fixed you may workaround it via registering the Factory (e.g. as Instance or as a singleton) and
specifying it via `ServiceInfo.Of<Factory>()` like this:

```cs
            var container = new Container();
    
            var factory = new Factory();
            container.RegisterInstance(factory);

            var factoryMethod = FactoryMethod.Of(typeof(Factory).GetMethods()
                .Single(m => m.Name == "Create" && m.IsGenericMethodDefinition), 
                ServiceInfo.Of<Factory>());
    
            container.Register(typeof(IAbstraction<>), made: Made.Of(factoryMethod: factoryMethod));

```

**Comment by hygehyge** [comment]
@dadhi Thanks for quick response. I don't want to register factory itself because somewhere in program, someone can use and change it.
So this time I'll define private static factory method and supply it to `FactoryMethod`.
When bug gets fixed, I'll check it.
Again, thank you for your time !!

**Comment by dadhi** [comment]
@hygehyge 

> I don't want to register factory itself because somewhere in program, someone can use and change it.

You may register it with the "secret" service key:

```cs
var secret = new object();
container.RegisterInstance(factory, serviceKey: secret);
var factoryMethod = FactoryMethod.Of(typeof(Factory).GetMethods()
                .Single(m => m.Name == "Create" && m.IsGenericMethodDefinition), 
                ServiceInfo.Of<Factory>(serviceKey: secret));
```

**Comment by hygehyge** [comment]
Sorry for late reply.
I had checked Ver.4.7.3 and the bug is gone !!
Thank you.
