### ISSUE TITLE
Regression in 5.0.0 when resolving Func<IEnumerable<IService>> with Parameter

### ISSUE THREAD

**Issue by Nefarion** [dadhi/DryIoc#470]
Hello,

I noticed a regression in 5.0.0 compared to 4.8.8. 
I tried to get a sample running, but it does not produce the error.

I am resolving a collection of services in a constructor like this:

```c#
class ServiceA
{
    public ServiceA(..., Func<ServiceA, IEnumerable<IServiceB>> onStart, ...)
    {
         ...
        onStart(this);
        ...
    }
}
```

I narrowed it down to the fact that SOME of the `IServiceB` implementations do not use `ServiceA` in their constructors, but some do.
It happily resolves the ones that do use ServiceA in their constructor, and fails with this error for the ones that do not:

```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type '<ServiceA>' to type 'System.Object[]'.
  Source=DryIoc
  StackTrace:
   at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result)
   at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result)
   at DryIoc.Interpreter.InterpretGetScopedOrSingletonViaFactoryDelegate(IResolverContext r, GetScopedOrSingletonViaFactoryDelegateExpression e, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs)
   at DryIoc.Interpreter.TryInterpretMethodCall(IResolverContext r, MethodCallExpression callExpr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result)
   at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result)
   at DryIoc.Interpreter.TryInterpret(IResolverContext r, Expression expr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs, Object& result)
   at DryIoc.Interpreter.TryInterpretNestedLambdaBodyAndUnwrapException(IResolverContext r, Expression bodyExpr, IParameterProvider paramExprs, Object paramValues, ParentLambdaArgs parentArgs)
   at DryIoc.Interpreter.<>c__DisplayClass3_0.<TryInterpretNestedLambda>b__4(Object arg)
   at DryIoc.Interpreter.<>c__DisplayClass9_0`2.<ConvertOneArgFunc>b__0(T a)
   at <ServiceA>..ctor(..., Document doc, Func`2 onDocStart, ...) in <snip>

```

For now, i reverted to 4.8.8 and everything works fine!
Thanks for your help!

**Comment by dadhi** [comment]
Thanks, good finding. I probably already know what is it based on the stacktrace. I will look into the problem.

**Comment by dadhi** [comment]
@Nefarion Could you provide the rest of the registrations required to resolve `ServiceA` because I have tried a simple test and the issue is not reproduced (see below). Also, what is your target platform?

```cs
using System;
using System.Collections.Generic;
using NUnit.Framework;

namespace DryIoc.IssuesTests
{
    [TestFixture]
    public class GHIssue470_Regression_v5_when_resolving_Func_of_IEnumerable_of_IService_with_Parameter
    {
        [Test]
        public void Test()
        {
            var c = new Container();

            c.Register<ServiceA>();
            c.Register<IServiceB, ServiceB1>();

            var a = c.Resolve<ServiceA>();
            Assert.IsInstanceOf<ServiceB1>(((IServiceB[])a.Services)[0]); // works fine
        }

        class ServiceA
        {
            public IEnumerable<IServiceB> Services;
            public ServiceA(Func<ServiceA, IEnumerable<IServiceB>> onStart)
            {
                Services = onStart(this);
            }
        }

        interface IServiceB {}
        class ServiceB1 : IServiceB {}
    }
}
```

**Comment by Nefarion** [comment]
@dadhi Okay, i was able to reproduce it:

```c#
using System;
using System.Collections.Generic;
using NUnit.Framework;

namespace DryIoc.IssuesTests
{
    [TestFixture]
    public class GHIssue470_Regression_v5_when_resolving_Func_of_IEnumerable_of_IService_with_Parameter
    {
        [Test]
        public void Test()
        {
            var container = new Container();
            container.Register<IServiceB, ServiceB>();
            container.Register<IDep, Dep>();
            container.Register<ServiceA>();
            container.Resolve<ServiceA>();
        }

        class ServiceA
        {
            public ServiceA(Func<ServiceA, IEnumerable<IServiceB>> services)
            {
                services(this);
            }
        }

        interface IServiceB { }
        interface IDep { }
        class Dep : IDep { }
        class ServiceB : IServiceB
        {
            public ServiceB(IResolver cont, IDep dep) { }
        }
    }
}
```

**Comment by dadhi** [comment]
@Nefarion DryIoc v5.0.1 with the fix is on NuGet
