### ISSUE TITLE
Microsoft.Extensions.DependencyInjection.OptionsServiceCollectionExtensions.AddOptions throws Error.UnableToSelectSinglePublicConstructorFromMultiple

### ISSUE THREAD

**Issue by Leon99** [dadhi/DryIoc#584]
Even though the MS Options pattern may not be very common but Microsoft.Extensions.Logging got 2B+ downloads, and it has Options as its dependency so the same error is thrown from `Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging()`.

IMHO worth fixing or, at least, documenting a workaround.

Repro: https://dotnetfiddle.net/vkLQts

Error:
```
DryIoc.ContainerException: code: Error.UnableToSelectSinglePublicConstructorFromMultiple;
message: Unable to select single public constructor from implementation type Microsoft.Extensions.Options.OptionsFactory<>:
Void .ctor(System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Options.IConfigureOptions`1[TOptions]], System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Options.IPostConfigureOptions`1[TOptions]]), 
Void .ctor(System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Options.IConfigureOptions`1[TOptions]], System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Options.IPostConfigureOptions`1[TOptions]], System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Options.IValidateOptions`1[TOptions]])
   at DryIoc.Throw.When(Boolean throwIfInvalid, Int32 error, Object arg0, Object arg1, Object arg2, Object arg3) in /_/src/DryIoc/Container.cs:line 14667
   at DryIoc.ReflectionFactory.ValidateAndNormalizeRegistration(Type serviceType, Object serviceKey, Boolean isStaticallyChecked, Rules rules, Boolean throwIfInvalid) in /_/src/DryIoc/Container.cs:line 12203
   at DryIoc.Container.Register(Factory factory, Type serviceType, Object serviceKey, Nullable`1 ifAlreadyRegistered, Boolean isStaticallyChecked) in /_/src/DryIoc/Container.cs:line 253
   at DryIoc.Microsoft.DependencyInjection.DryIocAdapter.RegisterDescriptor(IContainer container, ServiceDescriptor descriptor, IfAlreadyRegistered ifAlreadyRegistered, Object serviceKey) in /_/src/DryIoc.Microsoft.DependencyInjection/DryIocAdapter.cs:line 250
   at DryIoc.Microsoft.DependencyInjection.DryIocAdapter.RegisterDescriptor(IContainer container, ServiceDescriptor descriptor) in /_/src/DryIoc.Microsoft.DependencyInjection/DryIocAdapter.cs:line 239
   at DryIoc.Microsoft.DependencyInject
```

**Comment by dadhi** [comment]
Thanks for the finding and for the reproduction code. I will check for sure.

**Comment by dadhi** [comment]
Hi @Leon99,

The problem is that you are using the "bare-bone" container (`new Container()`) without the Rules conforming to the MS.DI.
Actually, method `Populate` is not your starting point and supposed to be used by the container with the proper rules (see below) or will be called automatically for you from the `WithDependencyInjectionAdapter` method or when using the `DryIocServiceProviderFactory`.

Here is the proper code:

```cs
// test gh issue 584
services.AddOptions();

// Will not work because the container is not conformed to the MS.DI rules!
// var containerIssue584 = new Container();

// Instead use this:
var containerIssue584_1 = new Container(Rules.MicrosoftDependencyInjectionRules);
containerIssue584_1.Populate(services);

// or better this:
var containerIssue584_2 = new Container().WithDependencyInjectionAdapter(services);
```

You may look at samples folder for the examples, in particular check the **samples/GHIssue520**, **samples/BlazorServerSide**

**Comment by Leon99** [comment]
Thanks @dadhi, much appreciated!
