### ISSUE TITLE
facing issue with DryIOC.dll.

### ISSUE THREAD

**Issue by AjayGogineni** [dadhi/DryIoc#655]
Hi I have upgraded my dotnet webapi 3.1 to 8 and DryIoc upgraded to latest stable version.
DryIOC 5.4.3
DryIoc.Microsft.DependencyInjection 6.2.0
in local windows machine i am able to run with out any errors.
but after moving to Linux Server i am getting issue.
Unhandled Exception exception as occurred while executing tht request.
at System.Reflection.RuntimeMethodInfo.Invoke()
at DryIoc.Inspector.TryInterpretMethodcall()

**Comment by dadhi** [comment]
Hi @AjayGogineni,

More details please. The full message error and the stack trace. Ideally, the test or the small reproducing the error.

Also, could you check if you have the error with the latest DryIoc v6.0.0-preview-07?

**Comment by AjayGogineni** [comment]
Fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandleMiddleware
An unhandled Exception has occured while executing the request
system.Rflection.TargetExceptoin: object does not match target type.
at system.Reflection.RuntimMethodINfo.Invoke()
at DryIoc.Interpreter.TryInterpretMethodcall()
in Visual studio have upto 5.4.2 only

**Comment by dadhi** [comment]
@AjayGogineni Could you try v6.0.0-preview-08 now?

**Comment by dadhi** [comment]
Closing, because no substantial details were provided
